---
# Python 3 with PostgreSQL
version: "3"

services:
  app:
    image: ghcr.io/promosquad/docker-dev:latest
    hostname: nyu
    ports:
      - 8080:8080
    volumes:
      - ..:/app
      - ~/.ssh/:/home/devops/.ssh/
    command: sleep infinity
    environment:
      FLASK_APP: service:app
      DATABASE_URI: postgres://postgres:postgres@postgres:5432/postgres
    networks:
      - dev
    depends_on:
      - postgres

  postgres:
    image: postgres:alpine
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres:/var/lib/postgresql/data
    networks:
      - dev

volumes:
  postgres:

networks:
  dev:
