name: Run Python Tests
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    # use a known build environment
    container: python:3.9-slim

    # Required services
    services:
      # Label used to access the service container
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: testdb
        ports:
          - 5432:5432
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    # Steps for the build
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: |
          apt-get update && apt-get install -y python3-selenium
          python -m pip install --upgrade pip wheel
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Run unit tests with nose
        run: nosetests
        env:
          DATABASE_URI: "postgres://postgres:postgres@postgres:5432/testdb"

      - name: Run BDD tests
        run: honcho start & (sleep 2 && behave)
        env:
          PORT: 8080
          DATABASE_URI: "postgres://postgres:postgres@postgres:5432/testdb"

      - name: Upload code coverage
        uses: codecov/codecov-action@v2
